### ISSUE TITLE
can't find reason for requirement on github.com/google/pprof@v0.0.0-20210407192527-94a9f03dee38

### ISSUE THREAD

**Issue by dervomsee** [caddy-dns/netcup#1]
I am trying to build caddy with netcup dns support. To achieve this I use the following Dockerfile:

```
FROM caddy:builder AS builder

RUN xcaddy build \
    --with github.com/caddy-dns/netcup

FROM caddy:latest

COPY --from=builder /usr/bin/caddy /usr/bin/caddy
```

When starting the build, the following error is generated:

````
#0 7.310 go: added golang.org/x/term v0.5.0
#0 7.310 go: added golang.org/x/text v0.6.0
#0 7.310 go: added golang.org/x/tools v0.2.0
#0 7.310 go: added google.golang.org/protobuf v1.28.1
#0 7.314 2023/02/15 10:05:38 [INFO] exec (timeout=0s): /usr/local/go/bin/go get -d -v github.com/caddy-dns/netcup github.com/caddyserver/caddy/v2@v2.6.3
#0 7.505 go: downloading github.com/caddy-dns/netcup v0.1.0
#0 11.24 panic: internal error: can't find reason for requirement on github.com/google/pprof@v0.0.0-20210407192527-94a9f03dee38
#0 11.24
#0 11.24 goroutine 1 [running]:
#0 11.24 cmd/go/internal/modget.(*resolver).updateBuildList.func1({{0xc000203458?, 0xc0005188e8?}, {0xc000116660?, 0xc000094d20?}})
#0 11.24        /usr/local/go/src/cmd/go/internal/modget/get.go:1760 +0x114
#0 11.24 cmd/go/internal/modget.(*resolver).updateBuildList(0xc0005b0d00, {0xb313d0, 0xc000028058}, {0x0, 0x0, 0x0})
#0 11.24        /usr/local/go/src/cmd/go/internal/modget/get.go:1765 +0x597
#0 11.24 cmd/go/internal/modget.(*resolver).resolveQueries(0xc0005b0d00, {0xb313d0, 0xc000028058}, {0xc0000575f0, 0x2, 0x472485?})
#0 11.24        /usr/local/go/src/cmd/go/internal/modget/get.go:1243 +0x1e5
#0 11.24 cmd/go/internal/modget.runGet({0xb313d0, 0xc000028058}, 0xc000026480?, {0xc000024220, 0x2, 0x2})
#0 11.24        /usr/local/go/src/cmd/go/internal/modget/get.go:314 +0x40b
#0 11.24 main.invoke(0xe2cfc0, {0xc0000241f0, 0x5, 0x5})
#0 11.24        /usr/local/go/src/cmd/go/main.go:225 +0x34e
#0 11.24 main.main()
#0 11.24        /usr/local/go/src/cmd/go/main.go:179 +0x7d1
#0 11.24 2023/02/15 10:05:42 [FATAL] exit status 2
------
failed to solve: process "/bin/sh -c xcaddy build     --with github.com/caddy-dns/netcup" did not complete successfully: exit code: 1
````

**Comment by mholt** [comment]
This is a known bug in the `go` command: https://github.com/caddyserver/caddy/issues/5301

Unfortunately we don't know when it will be fixed, as morale is quite low at Google at the moment (heard from a Go team member).

The linked issue has a workaround. Or this repo can upgrade to Caddy v2.6.4 in its go.mod.

**Comment by dervomsee** [comment]
Thank you for the comment. Interesting workaround. This fixes the bug for me now too.
